### ISSUE TITLE
Design: start page, close page, mode selection and level selection

### ISSUE THREAD

**Issue by annaiszhou** [WeibelLab-Teaching/CSE218_Fa19_StarX#7]

**Comment by una-020** [comment]
![Screen Shot 2019-11-10 at 6.30.10 PM.png](https://images.zenhubusercontent.com/5daf3a79262a760001d10006/4ac343a2-c2d9-4987-b21b-8fc790000889)![Screen Shot 2019-11-10 at 6.24.29 PM.png](https://images.zenhubusercontent.com/5daf3a79262a760001d10006/9d628afb-9358-4a92-9beb-f0c79a9caa88)![Screen Shot 2019-11-10 at 6.24.13 PM.png](https://images.zenhubusercontent.com/5daf3a79262a760001d10006/fba69577-2291-49a1-b266-c3325d4fa602)![Screen Shot 2019-11-10 at 6.24.02 PM.png](https://images.zenhubusercontent.com/5daf3a79262a760001d10006/5b77af06-6b2e-470c-9abe-d2df03ea0bcf)
